<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.6 setup script
 * Date: Thu, 05 Sep 2013 12:15:20 -0700
 */

/* Servers configuration */
$i = 0;

/* Server: photorewards [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'photorewards';
$cfg['Servers'][$i]['host'] = 'restore2.c2teljdmlsvx.us-east-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'ray';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */
?>
